global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter on all VMs
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - '192.168.123.10:9100'  # VM1 - node1
          - '192.168.123.11:9100'  # VM2 - node2
          - '192.168.123.12:9100'  # VM3 - node3
          - '192.168.123.20:9100'  # Proxy VM - proxy-node

  # Flask web applications
  - job_name: 'flask-webapp'
    static_configs:
      - targets:
          - '192.168.123.10:3000'  # VM1 Flask app
          - '192.168.123.11:3000'  # VM2 Flask app
          - '192.168.123.12:3000'  # VM3 Flask app
    metrics_path: '/health'
    scrape_interval: 30s

  # Nginx reverse proxy
  - job_name: 'nginx-proxy'
    static_configs:
      - targets: ['192.168.123.20:80']
    metrics_path: '/health'
    scrape_interval: 30s