all:
  children:
    webservers:
      hosts:
        vm1:
          ansible_host: localhost
          ansible_port: 2222
          ansible_user: "{{ lookup('env', 'VM1_USER') }}"
          ansible_ssh_pass: "{{ lookup('env', 'VM1_PASSWORD') }}"
          ansible_become_pass: "{{ lookup('env', 'VM1_PASSWORD') }}"
          vm_ip: 192.168.123.10
          hostname: node1
        vm2:
          ansible_host: localhost
          ansible_port: 2223
          ansible_user: "{{ lookup('env', 'VM2_USER') }}"
          ansible_ssh_pass: "{{ lookup('env', 'VM2_PASSWORD') }}"
          ansible_become_pass: "{{ lookup('env', 'VM2_PASSWORD') }}"
          vm_ip: 192.168.123.11
          hostname: node2
        vm3:
          ansible_host: localhost
          ansible_port: 2224
          ansible_user: "{{ lookup('env', 'VM3_USER') }}"
          ansible_ssh_pass: "{{ lookup('env', 'VM3_PASSWORD') }}"
          ansible_become_pass: "{{ lookup('env', 'VM3_PASSWORD') }}"
          vm_ip: 192.168.123.12
          hostname: node3
    proxy:
      hosts:
        proxy-vm:
          ansible_host: localhost
          ansible_port: 2225
          ansible_user: "{{ lookup('env', 'PROXY_USER') }}"
          ansible_ssh_pass: "{{ lookup('env', 'VM4_PASSWORD') }}"
          ansible_become_pass: "{{ lookup('env', 'VM4_PASSWORD') }}"
          vm_ip: 192.168.123.20
          hostname: proxy-node
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'